### PR TITLE
Typecasted PowerKW in both places

### PR DESCRIPTION
**Pull request by aryanbhosale**
# Pull Request

## Description

_Please delete the italicised instruction text!
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. List any dependencies that are required for this change._

Fixes #

## How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration_

- [ ] Yes

_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

- [ ] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
Can you check the tests pass locally please?

**Comment by aryanbhosale** [comment]
> Can you check the tests pass locally please?

Is there a command for running local tests for the changes I've made particularly? Or should I run the test files that are already there in the repository?

**Comment by peterdudfield** [comment]
> > Can you check the tests pass locally please?
> 
> Is there a command for running local tests for the changes I've made particularly? Or should I run the test files that are already there in the repository?

Should be `pytest`, if this is right, could you add how to run tests to the readme.md?

**Comment by aryanbhosale** [comment]
> > > Can you check the tests pass locally please?
> > 
> > 
> > Is there a command for running local tests for the changes I've made particularly? Or should I run the test files that are already there in the repository?
> 
> Should be `pytest`, if this is right, could you add how to run tests to the readme.md?

Sure! I could do that.

**Comment by aryanbhosale** [comment]
> > > Can you check the tests pass locally please?
> > 
> > 
> > Is there a command for running local tests for the changes I've made particularly? Or should I run the test files that are already there in the repository?
> 
> Should be `pytest`, if this is right, could you add how to run tests to the readme.md?

I'm unable to use ```pytest``` , can you please help me here?
I installed it using ```pip install .``` and tried to run using ```pytest```, but it doesn't recognize the command.

**Comment by peterdudfield** [comment]
I think you need python 3.11

**Comment by aryanbhosale** [comment]
> > > > Can you check the tests pass locally please?
> > > 
> > > 
> > > Is there a command for running local tests for the changes I've made particularly? Or should I run the test files that are already there in the repository?
> > 
> > 
> > Should be `pytest`, if this is right, could you add how to run tests to the readme.md?
> 
> I'm unable to use `pytest` , can you please help me here? I installed it using `pip install .` and tried to run using `pytest`, but it doesn't recognize the command.


> > > > Can you check the tests pass locally please?
> > > 
> > > 
> > > Is there a command for running local tests for the changes I've made particularly? Or should I run the test files that are already there in the repository?
> > 
> > 
> > Should be `pytest`, if this is right, could you add how to run tests to the readme.md?
> 
> I'm unable to use `pytest` , can you please help me here? I installed it using `pip install -e .` and tried to run using `pytest`, but it doesn't recognize the command. I see this error "Could not find a version that satisfies the requirement pvsite-datamodel>=1.0.10"

I wonder if ```"pvsite-datamodel >= 1.0.10",``` this line should be reversed(<=) since  the available models seem to be from these:
from versions: 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.1.16, 0.1.17, 0.1.18, 0.1.19, 0.1.20, 0.1.21, 0.1.22, 0.1.23, 0.1.24, 0.1.25, 0.1.26, 0.1.27, 0.1.28, 0.1.29, 0.1.30, 0.1.31, 0.1.32, 0.1.33, 0.1.34, 0.1.35, 1.0.0, 1.0.1, 1.0.2, 1.0.3

**Comment by aryanbhosale** [comment]
> I think you need python 3.11

Okay makes sense, will change interpreter

**Comment by aryanbhosale** [comment]
> I think you need python 3.11

note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
Successfully built india-api
Failed to build pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects

now it shows this, i tried reinstalling pandas but the error persists

**Comment by peterdudfield** [comment]
> > I think you need python 3.11
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for pandas Successfully built india-api Failed to build pandas ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects
> 
> now it shows this, i tried reinstalling pandas but the error persists

try python 3.12? maybe?

**Comment by aryanbhosale** [comment]
> > > I think you need python 3.11
> > 
> > note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for pandas Successfully built india-api Failed to build pandas ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects
> > 
> > now it shows this, i tried reinstalling pandas but the error persists
> 
> try python 3.12? maybe?

I did, still no luck :(
Ill try some more fixes regarding this and look it up a bit

**Comment by peterdudfield** [comment]
> > > > I think you need python 3.11
> > > 
> > > 
> > > note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for pandas Successfully built india-api Failed to build pandas ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects
> > > now it shows this, i tried reinstalling pandas but the error persists
> > 
> > 
> > try python 3.12? maybe?
> 
> I did, still no luck :( Ill try some more fixes regarding this and look it up a bit

what system you using?

**Comment by aryanbhosale** [comment]
> > > > > I think you need python 3.11
> > > > 
> > > > 
> > > > note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for pandas Successfully built india-api Failed to build pandas ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects
> > > > now it shows this, i tried reinstalling pandas but the error persists
> > > 
> > > 
> > > try python 3.12? maybe?
> > 
> > I did, still no luck :( Ill try some more fixes regarding this and look it up a bit
> 
> what system you using? 

I'm using ubuntu, does a vm count?

**Comment by peterdudfield** [comment]
> > > > > > I think you need python 3.11
> > > > > 
> > > > > 
> > > > > note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for pandas Successfully built india-api Failed to build pandas ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects
> > > > > now it shows this, i tried reinstalling pandas but the error persists
> > > > 
> > > > 
> > > > try python 3.12? maybe?
> > > 
> > > 
> > > I did, still no luck :( Ill try some more fixes regarding this and look it up a bit
> > 
> > 
> > what system you using?
> 
> I'm using ubuntu, does a vm count?

so i general you cant install pandas? Feels like a different problem right?

**Comment by aryanbhosale** [comment]
> > > > > > > I think you need python 3.11
> > > > > > 
> > > > > > 
> > > > > > note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for pandas Successfully built india-api Failed to build pandas ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects
> > > > > > now it shows this, i tried reinstalling pandas but the error persists
> > > > > 
> > > > > 
> > > > > try python 3.12? maybe?
> > > > 
> > > > 
> > > > I did, still no luck :( Ill try some more fixes regarding this and look it up a bit
> > > 
> > > 
> > > what system you using?
> > 
> > 
> > I'm using ubuntu, does a vm count?
> 
> so i general you cant install pandas? Feels like a different problem right?

I can individually(separate for pip install -e .) by just pip install pandas, but can't together with the instructions in the readme

**Pull request closed without merging**
